#!/usr/bin/env ansible-playbook


- name: run ansible on android
  hosts: termux
  gather_facts: no
  tasks:

    - name: setup storage on phone to allow access to internal storeage
      debug:
        msg: run `termux-setup-storage` on your phone

    - name: pkg install packages
      command: pkg install --yes {{item}}
      loop:
        - root-repo
        - x11-repo
        - unstable-repo
        - termux-api
        - libxml2
        - libxslt
        - python
        - openssh
        - ffmpeg
        - zsh
        - curl
        - wget
        - vim
        - git
        - htop
        - rsync

    - name: pip install packages
      pip:
        name:
          - pip
          - ipython
          - youtube-dl
          - pymusic-dl
          - gplaycli
          - ssh-import-id

    - name: render gplaycli.conf
      template:
        src: "templates/gplaycli.conf"
        # put it in home, so we can run gplaycli from there
        dest: "bin/gplaycli.conf"
      tags:
        - files

    - name: sync bin dir to remote
      synchronize:
        src: "bin/"
        dest: "bin/"
      tags:
        - files
