#!/usr/bin/env ansible-playbook


- name: run ansible on android
  hosts: termux
  gather_facts: no
  tasks:

    - name: setup storage on phone to allow access to internal storeage
      debug:
        msg: run `termux-setup-storage` on your phone

    - name: pkg install packages
      command: pkg install --yes {{item}}
      loop:
        - root-repo
        - x11-repo
        - unstable-repo
        - libxml2
        - libxslt
        - python
        - openssh
        - ffmpeg
        - zsh
        - curl
        - wget
        - vim
        - git
        - htop

    - name: pip install packages
      pip:
        name:
          - pip
          - ipython
          - youtube-dl
          - pymusic-dl
          - gplaycli
          - ssh-import-id

    - name: create gplaycli.conf
      template:
        src: "templates/gplaycli.conf"
        # put it in home, so we can run gplaycli from there
        dest: "gplaycli.conf"
      tags:
        - files

    - name: create bin/termux-url-opener
      template:
        src: "templates/{{ item }}"
        dest: "bin/{{ item }}"
        mode: "0755"
      loop:
        - termux-url-opener
        - termux-file-editor
      tags:
        - files
