#!/usr/bin/env ansible-playbook


- name: run ansible on android
  hosts: termux
  gather_facts: no
  tasks:

    - name: pkg install packages
      command: pkg install --yes {{item}}
      loop:
        - root-repo
        - x11-repo
        - unstable-repo
        - libxml2
        - libxslt
        - python
        - openssh
        - ffmpeg
        - zsh
        - curl
        - wget
        - vim
        - git

    - name: pip install packages
      pip:
        name:
          - pip
          - ipython
          - youtube-dl
          - pymusic-dl
          - gplaycli
          - ssh-import-id
