#!/usr/bin/env ansible-playbook


- name: run ansible on android
  hosts: termux
  gather_facts: no
  tasks:

    - name: setup storage on phone to allow access to internal storeage
      debug:
        msg: run `termux-setup-storage` on your phone

    - name: pkg install packages
      command: pkg install --yes {{item}}
      loop:
        - root-repo
        - x11-repo
        - unstable-repo
        - termux-api
        - libxml2
        - libxslt
        - python
        - openssh
        - ffmpeg
        - zsh
        - curl
        - wget
        - vim
        - git
        - htop
        - rsync
        - neofetch

    - name: pip install packages
      pip:
        name:
          - pip
          - ipython
          - youtube-dlc
          - pymusic-dl
          - gplaycli
          - ssh-import-id

    - name: make dirs
      file:
        path: bin/
        state: directory
        mode: '0755'

    - name: render gplaycli.conf
      template:
        src: "templates/gplaycli.conf"
        dest: "bin/gplaycli.conf"
      tags:
        - files

    - name: sync bin dir to remote
      synchronize:
        src: "bin/"
        dest: "bin/"
      tags:
        - files

    - name: download oh-my-zsh install script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ./install.sh
        mode: '0755'
      tags: oh-my-zsh

    - name: run oh-my-zsh install script
      command: chsh -s zsh && ./install.sh
      tags: oh-my-zsh

    - name: download apks
      get_url:
        url: "{{ item }}"
        dest: "storage/downloads/"
      loop:
        - https://f-droid.org/F-Droid.apk
        - https://dl.cmbimg.com/AndroidClient/CMBMobileBank.apk
      tags: apk
